// Code generated by mockery v1.0.0. DO NOT EDIT.

// NOTE: run 'make update-mocks' to regenerate

package light

import mock "github.com/stretchr/testify/mock"

// MockOLAClient is an autogenerated mock type for the OLAClient type
type MockOLAClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockOLAClient) Close() {
	_m.Called()
}

// SendDmx provides a mock function with given fields: universe, values
func (_m *MockOLAClient) SendDmx(universe int, values []byte) (bool, error) {
	ret := _m.Called(universe, values)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, []byte) bool); ok {
		r0 = rf(universe, values)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, []byte) error); ok {
		r1 = rf(universe, values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
