// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	proto/api.proto

It has these top-level messages:
	Ping
	MarshalledJSON
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ping struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ping) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MarshalledJSON struct {
	Kind string `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *MarshalledJSON) Reset()                    { *m = MarshalledJSON{} }
func (m *MarshalledJSON) String() string            { return proto.CompactTextString(m) }
func (*MarshalledJSON) ProtoMessage()               {}
func (*MarshalledJSON) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MarshalledJSON) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *MarshalledJSON) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Ping)(nil), "Ping")
	proto.RegisterType((*MarshalledJSON)(nil), "MarshalledJSON")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	GetPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Ping, error)
	StreamCueMaster(ctx context.Context, in *Ping, opts ...grpc.CallOption) (API_StreamCueMasterClient, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Ping, error) {
	out := new(Ping)
	err := grpc.Invoke(ctx, "/API/GetPing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) StreamCueMaster(ctx context.Context, in *Ping, opts ...grpc.CallOption) (API_StreamCueMasterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_API_serviceDesc.Streams[0], c.cc, "/API/StreamCueMaster", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIStreamCueMasterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_StreamCueMasterClient interface {
	Recv() (*MarshalledJSON, error)
	grpc.ClientStream
}

type aPIStreamCueMasterClient struct {
	grpc.ClientStream
}

func (x *aPIStreamCueMasterClient) Recv() (*MarshalledJSON, error) {
	m := new(MarshalledJSON)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for API service

type APIServer interface {
	GetPing(context.Context, *Ping) (*Ping, error)
	StreamCueMaster(*Ping, API_StreamCueMasterServer) error
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/GetPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetPing(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_StreamCueMaster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Ping)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).StreamCueMaster(m, &aPIStreamCueMasterServer{stream})
}

type API_StreamCueMasterServer interface {
	Send(*MarshalledJSON) error
	grpc.ServerStream
}

type aPIStreamCueMasterServer struct {
	grpc.ServerStream
}

func (x *aPIStreamCueMasterServer) Send(m *MarshalledJSON) error {
	return x.ServerStream.SendMsg(m)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPing",
			Handler:    _API_GetPing_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCueMaster",
			Handler:       _API_StreamCueMaster_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/api.proto",
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2c, 0xc8, 0xd4, 0x03, 0xb3, 0x94, 0x14, 0xb8, 0x58, 0x02, 0x32, 0xf3, 0xd2,
	0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x60, 0x5c, 0x25, 0x0b, 0x2e, 0x3e, 0xdf, 0xc4, 0xa2, 0xe2, 0x8c, 0xc4, 0x9c, 0x9c,
	0xd4, 0x14, 0xaf, 0x60, 0x7f, 0x3f, 0x21, 0x21, 0x2e, 0x96, 0xec, 0xcc, 0xbc, 0x14, 0xa8, 0x42,
	0x30, 0x1b, 0x24, 0x96, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66,
	0x1b, 0xf9, 0x73, 0x31, 0x3b, 0x06, 0x78, 0x0a, 0x49, 0x72, 0xb1, 0xbb, 0xa7, 0x96, 0x80, 0x6d,
	0x61, 0xd5, 0x03, 0x51, 0x52, 0x10, 0x4a, 0x89, 0x41, 0x48, 0x97, 0x8b, 0x3f, 0xb8, 0xa4, 0x28,
	0x35, 0x31, 0xd7, 0xb9, 0x34, 0xd5, 0x37, 0xb1, 0xb8, 0x24, 0xb5, 0x08, 0xa6, 0x84, 0x5f, 0x0f,
	0xd5, 0x52, 0x25, 0x06, 0x03, 0xc6, 0x24, 0x36, 0xb0, 0x9b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0xf0, 0xa3, 0x6c, 0xc6, 0x00, 0x00, 0x00,
}
